name: hello-world
'on': push
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          cd test-repo-allure
          python -m pip install
          pip install pytest
          pip install allure-pytest

      - name: API component tests
        run: |
          cd test-repo-allure
          pytest -v -s --alluredir=reports
          
