name: Test Automation
'on': push
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
      - name: Clone Repository
        run: |
          git clone https://github.com/HimanshuQA87/test-repo-allure.git

      - name: API component tests
        run: |
          cd test-repo-allure
          pytest -v -s --alluredir=target/allure-results
      - name : Check Allure results folder
        run: |
          ls -l target/allure-results
          
      # #Allure
      # - name: Get Allure history
      #   uses: actions/checkout@v2
      #   if: always()
      #   continue-on-error: true
      #   with:
      #     ref: gh-pages
      #     path: gh-pages

      # - name: Allure Report action from marketplace
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   id: allure-report
      #   with:
      #     allure_results: target/allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history

      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history

          
