name: Test Automation
'on': push
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
      - name: Clone Repository
        run: |
          git clone https://github.com/HimanshuQA87/test-repo-allure.git

      - name: API component tests
        run: |
          cd test-repo-allure
          pytest -v -s --alluredir=allure-results

          
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.tgz
          tar -xzvf allure-2.15.0.tgz
          sudo ln -s allure-2.15.0/bin/allure /usr/bin/allure
          allure --version # Verify installation
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

          
