name: hello-world
'on': push
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
      - name: Clone Repository
        run: |
          git clone https://github.com/HimanshuQA87/test-repo-allure.git

      - name: API component tests
        run: |
          cd test-repo-allure
          pytest -v -s --alluredir=reports
      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: test-repo-allure/reports
      - name: Create Artifact Link
        run: |
            gh pr comment ${{ github.event.number }} -b "Allure Report: [View Allure Report](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/artifacts/allure-reports)"
            if: success() && github.event_name == 'pull_request'
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
