name: hello-world
'on': push
jobs:
  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
      - name: Clone Repository
        run: |
          git clone https://github.com/HimanshuQA87/test-repo-allure.git

      - name: API component tests
        run: |
          cd test-repo-allure
          pytest -v -s --alluredir=reports
      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: test-repo-allure/reports
      - name: Create Artifact Link
        run: |
            echo "Allure report is available at: ${{ github.server }}/HimanshuQA87/test-repo-allure/actions/runs/${{ github.run_id }}/artifacts/allure-report"
          
